# Generated by Django 4.2.25 on 2025-10-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=200)),
                ("creditos", models.PositiveSmallIntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("semestre", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("obrigatoria", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisitos",
                    models.ManyToManyField(
                        blank=True, related_name="dependentes", to="pages.disciplina"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "disciplinas",
                    models.ManyToManyField(
                        blank=True, related_name="professores", to="pages.disciplina"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=200)),
                ("creditos_totais", models.PositiveIntegerField()),
                (
                    "disciplinas",
                    models.ManyToManyField(
                        blank=True, related_name="cursos", to="pages.disciplina"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("ano", models.PositiveSmallIntegerField()),
                ("semestre", models.PositiveSmallIntegerField()),
                ("capacidade", models.PositiveIntegerField(default=30)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="pages.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turmas",
                        to="pages.professor",
                    ),
                ),
            ],
            options={
                "ordering": ["-ano", "-semestre", "disciplina"],
                "unique_together": {("disciplina", "ano", "semestre", "codigo")},
            },
        ),
    ]
